### PR TITLE
Tuning launcher

### PR DESCRIPTION
**Pull request by tri-vu-12**

### CODE REVIEW

**Comment by jnallard** [comment]
Test values we saw for getting k_f:
image

k_f = (PERCENT_POWER X 1023) / OBSERVED_VELOCITY

https://docs.ctre-phoenix.com/en/stable/ch16_ClosedLoop.html#how-to-calculate-kf

**Review by jnallard — APPROVED** [review]
Reviewed together

**Comment by tri-vu-12** [comment]
Looks good :)

**Comment by tri-vu-12** [comment]
Fixes #85

**Comment by tri-vu-12** [comment]
Fixes #48

**Pull request merged**
