### PR TITLE
Updated DriveToPosition so it uses PID

### PR DESCRIPTION
**Pull request by tri-vu-12**

### CODE REVIEW

**Comment by acezyx** [comment]
Looks goood

**Comment by tri-vu-12** [comment]
Fixes #86

**Comment by tri-vu-12** [comment]
Fixes #58

**Comment by tri-vu-12** [comment]
Fixes #43

**Review by jnallard — APPROVED** [review]
Going to merge despite not fully being tested. We made some other changes based off this and want to move on more quickly.

**Pull request merged**
