### PR TITLE
Creates a SwerveModulePositionEnum

### PR DESCRIPTION
**Pull request by jnallard**
Creates an enum that makes the code more readable for which swerve module we're talking about

### CODE REVIEW

**Review by Joojnini — APPROVED** [review]
I really like these changes; everything looks good

**Review by croooutons — APPROVED** [review]
everything looks good to me

**Comment by NinjaKiwi1011** [comment]
Looks good :)

**Review by NinjaKiwi1011 — APPROVED** [review]
Reviewed as a group :)

**Pull request merged**
